version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
  students:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db