spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

